# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SocialNetworkNew' do
pod 'AFNetworking', '~> 2.6'
pod "VK-ios-sdk"
end

target 'SocialNetworkNewTests' do
pod 'AFNetworking', '~> 2.6'
pod "VK-ios-sdk"
end

